x = 1

#0-9\
#hover to get info??
'''
for i in range (10):
    #if x is even
    if i % 2 == 0:
        x += 1 
        print(x)

print(f"x is {x}")


'''


'''

for i in range (10):
    #if x is even
    if x % 2 == 0:
        x += 1 
        print(x)

print(f"x is {x}")



'''


for i in range (10):
    #if x is even
    if x % 2 == 0:
        x += 1 
        print(x)
    if i % 2 ==0:
        x -= 1
print(f"x is {x}")